site_name: Prompt Engineering Collection
theme:
  name: material
  palette:
    scheme: slate
    primary: deep purple
    accent: purple
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight

plugins:
  - search
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - def_list
  - attr_list
  - md_in_html

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.11/clipboard.min.js
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Contributing: contributing.md
  - About: about.md
  - Agent Improvements: agent-improvements.md
  - Prompts:
    - Overview: prompts/overview.md
    - Education: prompts/education.md
    - Misc: prompts/misc.md