site_name: Prompt Engineering Collection
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - tags

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - def_list
  - tables
  - meta
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.8/clipboard.min.js
  - javascripts/extra.js

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Prompts:
    - Overview: prompts/overview.md
    - Academic: prompts/academic.md
    - Art: prompts/art.md
    - Content Creation: prompts/content-creation.md
    - Data: prompts/data.md
    - Developer: prompts/developer.md
    - Education: prompts/education.md
    - Healthcare: prompts/healthcare.md
    - Legal: prompts/legal.md
    - Meta: prompts/meta.md
    - Product: prompts/product.md
    - QA: prompts/qa.md
  - Getting Started: getting-started.md
  - Contributing: contributing.md