name: Documentation
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs-material
          pip install mkdocs-minify-plugin
          pip install mkdocs-git-revision-date-localized-plugin
          pip install pillow cairosvg
          pip install pyyaml
          pip install python-frontmatter

      - name: Debug workspace
        run: |
          echo "Current directory structure:"
          ls -R
          echo "Content of docs/stylesheets:"
          ls -la docs/stylesheets/
          echo "Content of docs/javascripts:"
          ls -la docs/javascripts/ || mkdir -p docs/javascripts
          echo "Content of extra.css:"
          cat docs/stylesheets/extra.css

      - name: Generate gallery
        run: |
          chmod +x scripts/generate_gallery.py
          python scripts/generate_gallery.py

      - name: Ensure assets directories
        run: |
          mkdir -p site/stylesheets
          mkdir -p site/javascripts
          cp -v docs/stylesheets/extra.css site/stylesheets/
          cp -v docs/javascripts/extra.js site/javascripts/ || echo "No extra.js found"
          echo "Content of site/stylesheets after copy:"
          ls -la site/stylesheets/
          echo "Content of site/javascripts after copy:"
          ls -la site/javascripts/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build site
        run: |
          mkdocs build --verbose
          echo "Content of site directory after build:"
          ls -R site/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 