name: Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'prompts/**'
      - 'mkdocs.yml'
      - '.github/workflows/documentation.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt
          pip install python-frontmatter
      
      - name: Generate Gallery
        run: |
          mkdir -p docs/assets/data
          python scripts/generate_gallery.py
      
      - name: Build site
        run: |
          mkdocs build --verbose
      
      - name: Ensure .nojekyll exists
        run: |
          touch docs/.nojekyll
          mkdir -p site
          touch site/.nojekyll
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      
      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'site'
      
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        id: deployment
        uses: actions/deploy-pages@v2 