name: Generate Gallery

on:
  push:
    paths:
      - 'prompts/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'
          
      - name: Debug Environment
        run: |
          echo "Python version:"
          python --version
          echo "Pip version:"
          pip --version
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Requirements.txt contents:"
          cat requirements.txt
          echo "Python executable path:"
          which python
          echo "Pip executable path:"
          which pip
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r requirements.txt
          python -m pip install python-frontmatter --upgrade
          echo "Installed packages:"
          pip list
          echo "Python path:"
          python -c "import sys; print('\n'.join(sys.path))"
          
      - name: Verify Python environment
        run: |
          echo "Checking Python environment..."
          python -c "import sys; print(f'Python version: {sys.version}')"
          python -c "import site; print(f'Site packages: {site.getsitepackages()}')"
          python -c "import frontmatter; print(f'Frontmatter found at: {frontmatter.__file__}')"
        
      - name: Generate gallery
        run: |
          python scripts/generate_gallery.py
        
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/index.md
          git diff --quiet && git diff --staged --quiet || git commit -m "Update gallery"
          git push 